-- next-db-admin schema
-- Run once in the database pointed to by POSTGRES_URL (used for logging only)

CREATE TABLE IF NOT EXISTS public.xlg_logging (
    lg_lgid         integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lg_severity     character(1),
    lg_caller       character varying DEFAULT '',
    lg_functionname character varying NOT NULL,
    lg_msg          character varying NOT NULL,
    lg_datetime     timestamp with time zone NOT NULL,
    CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid)
);
